# Generated by Django 5.0.6 on 2024-05-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_id', models.IntegerField()),
                ('xyz_campaign_id', models.IntegerField()),
                ('fb_campaign_id', models.IntegerField()),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=1)),
                ('interest', models.IntegerField()),
                ('impressions', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('spent', models.FloatField()),
                ('total_conversion', models.IntegerField()),
                ('approved_conversion', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
